### ISSUE TITLE
Land Ownership?

### ISSUE THREAD

**Issue by sitlaBarry** [agrc/deq-spills#45]
Can land ownership be added to this map? It's critical data for this type of map.

**Comment by stdavis** [comment]
It could be added. Are you working with Marc Wade or Harold at DEQ on this project?

**Comment by sitlaBarry** [comment]
We're working our way through the bureaucratic maze right now.

**Comment by stdavis** [comment]
Good luck with that. :)

**Comment by stdavis** [comment]
Closed with 098efd3 and deployed as v2.5.0.

**Comment by sitlaBarry** [comment]
Thanks!
